---
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 80

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

...
