---
gemAuthor: Thomas Boerger
gemAuthorEmail: thomas@webhippie.de
gemDescription: OpenAPI client for Kleister
gemHomepage: https://github.com/kleister/kleister-ruby
gemLicense: Apache-2.0
gemName: kleister
gemSummary: Manage mod packs for Minecraft
gemVersion: 1.15.1
moduleName: Kleister
library: faraday
enablePostProcessFile: true

...
