# Kleister OpenAPI
#
# API definition for Kleister, manage mod packs for Minecraft
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: kleister@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.13.0
#

require 'spec_helper'
require 'json'

# Unit tests for Kleister::FabricApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FabricApi' do
  before do
    # run before each test
    @api_instance = Kleister::FabricApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FabricApi' do
    it 'should create an instance of FabricApi' do
      expect(@api_instance).to be_instance_of(Kleister::FabricApi)
    end
  end

  # unit tests for attach_fabric_to_build
  # Attach a build to a Fabric version
  # @param fabric_id A fabric identifier or slug
  # @param attach_minecraft_to_build_request The fabric build data to create or update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_fabric_to_build test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_fabric_from_build
  # Unlink a build from a Fabric version
  # @param fabric_id A fabric identifier or slug
  # @param attach_minecraft_to_build_request The fabric build data to create or update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_fabric_from_build test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_fabric_builds
  # Fetch the builds attached to a Fabric version
  # @param fabric_id A fabric identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [ListFabricBuilds200Response]
  describe 'list_fabric_builds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_fabrics
  # Fetch the available Fabric versions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @return [ListFabrics200Response]
  describe 'list_fabrics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_fabric
  # Update the available Fabric versions
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'update_fabric test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
