# Kleister OpenAPI
#
# API definition for Kleister, manage mod packs for Minecraft
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: kleister@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'

# Unit tests for Kleister::MinecraftApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MinecraftApi' do
  before do
    # run before each test
    @api_instance = Kleister::MinecraftApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MinecraftApi' do
    it 'should create an instance of MinecraftApi' do
      expect(@api_instance).to be_instance_of(Kleister::MinecraftApi)
    end
  end

  # unit tests for attach_minecraft_to_build
  # Attach a build to a Minecraft version
  # @param minecraft_id A minecraft identifier or slug
  # @param attach_minecraft_to_build_request The minecraft build data to create or update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_minecraft_to_build test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_minecraft_from_build
  # Unlink a build from a Minecraft version
  # @param minecraft_id A minecraft identifier or slug
  # @param attach_minecraft_to_build_request The minecraft build data to create or update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_minecraft_from_build test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_minecraft_builds
  # Fetch the builds attached to a Minecraft version
  # @param minecraft_id A minecraft identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [ListMinecraftBuilds200Response]
  describe 'list_minecraft_builds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_minecrafts
  # Fetch the available Minecraft versions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @return [ListMinecrafts200Response]
  describe 'list_minecrafts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_minecraft
  # Update the available Minecraft versions
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'update_minecraft test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
