=begin
#Kleister OpenAPI

#API definition for Kleister, manage mod packs for Minecraft

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kleister::MinecraftApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MinecraftApi' do
  before do
    # run before each test
    @api_instance = Kleister::MinecraftApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MinecraftApi' do
    it 'should create an instance of MinecraftApi' do
      expect(@api_instance).to be_instance_of(Kleister::MinecraftApi)
    end
  end

  # unit tests for append_minecraft_to_build
  # Assign a build to a Minecraft version
  # @param minecraft_id A minecraft UUID or slug
  # @param minecraft_build The build data to append
  # @param [Hash] opts the optional parameters
  # @return [Array<Build>]
  describe 'append_minecraft_to_build test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_minecraft_from_build
  # Unlink a build from a Minecraft version
  # @param minecraft_id A minecraft UUID or slug
  # @param minecraft_build The build data to unlink
  # @param [Hash] opts the optional parameters
  # @return [Array<Build>]
  describe 'delete_minecraft_from_build test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_minecraft_builds
  # Fetch the builds assigned to a Minecraft version
  # @param minecraft_id A minecraft UUID or slug
  # @param [Hash] opts the optional parameters
  # @return [Array<Build>]
  describe 'list_minecraft_builds test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_minecrafts
  # Fetch the available Minecraft versions
  # @param [Hash] opts the optional parameters
  # @return [Array<Minecraft>]
  describe 'list_minecrafts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_minecrafts
  # Search for available Minecraft versions
  # @param minecraft_id A search token to search Minecraft versions
  # @param [Hash] opts the optional parameters
  # @return [Array<Minecraft>]
  describe 'search_minecrafts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_minecraft
  # Update the available Minecraft versions
  # @param [Hash] opts the optional parameters
  # @return [GeneralError]
  describe 'update_minecraft test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
