# Kleister OpenAPI
#
# API definition for Kleister, manage mod packs for Minecraft
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: kleister@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.6.0
#

require 'spec_helper'
require 'json'

# Unit tests for Kleister::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = Kleister::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(Kleister::UserApi)
    end
  end

  # unit tests for attach_user_to_mod
  # Attach a mod to user
  # @param user_id A user identifier or slug
  # @param user_mod_params The user mod data to attach
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_user_to_mod test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for attach_user_to_pack
  # Attach a pack to user
  # @param user_id A user identifier or slug
  # @param user_pack_params The user pack data to attach
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_user_to_pack test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for attach_user_to_team
  # Attach a team to user
  # @param user_id A user identifier or slug
  # @param user_team_params The user team data to attach
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_user_to_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_user
  # Create a new user
  # @param user The user data to create
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'create_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user
  # Delete a specific user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user_from_mod
  # Unlink a mod from user
  # @param user_id A user identifier or slug
  # @param user_mod_params The user mod data to unlink
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user_from_mod test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user_from_pack
  # Unlink a pack from user
  # @param user_id A user identifier or slug
  # @param user_pack_params The user pack data to unlink
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user_from_pack test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user_from_team
  # Unlink a team from user
  # @param user_id A user identifier or slug
  # @param user_team_params The user team data to unlink
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user_from_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_user_mods
  # Fetch all mods attached to user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [UserMods]
  describe 'list_user_mods test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_user_packs
  # Fetch all packs attached to user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [UserPacks]
  describe 'list_user_packs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_user_teams
  # Fetch all teams attached to user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [UserTeams]
  describe 'list_user_teams test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users
  # Fetch all available users
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [Users]
  describe 'list_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permit_user_mod
  # Update mod perms for user
  # @param user_id A user identifier or slug
  # @param user_mod_params The user mod data to update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'permit_user_mod test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permit_user_pack
  # Update pack perms for user
  # @param user_id A user identifier or slug
  # @param user_pack_params The user pack data to update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'permit_user_pack test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permit_user_team
  # Update team perms for user
  # @param user_id A user identifier or slug
  # @param user_team_params The user team data to update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'permit_user_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_user
  # Fetch a specific user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'show_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user
  # Update a specific user
  # @param user_id A user identifier or slug
  # @param user The user data to update
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'update_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
