# Kleister OpenAPI
#
# API definition for Kleister, manage mod packs for Minecraft
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: kleister@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.13.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kleister::PermitGroupModRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kleister::PermitGroupModRequest do
  let(:instance) { Kleister::PermitGroupModRequest.new }

  describe 'test an instance of PermitGroupModRequest' do
    it 'should create an instance of PermitGroupModRequest' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(Kleister::PermitGroupModRequest)
    end
  end

  describe 'test attribute "mod"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "perm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
