---
name: changes

"on":
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Build changelog
        uses: actionhippie/calens@v1
        with:
          target: CHANGELOG.md

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@kleister.eu
          add: CHANGELOG.md
          message: "docs: automated changelog update"
          push: true
          commit: --signoff

...
